### ISSUE TITLE
Please Support os-client-config

### ISSUE THREAD

**Issue by yfried** [redhat-openstack/python-tempestconf#2]
As a user, I would like to use clouds.yml files instead of openstackrc files, the same way I use all openstack utilities (shade, ansible, InfraRed, openstack-*client, etc...)

All openstack utilities should have built-in support for [os-client-config](http://docs.openstack.org/developer/os-client-config), deprecating openstackrc files (but still supporting them), and supporting "clouds.yml" files

Ideally, invocation would look like:

```bash
tempest-config --os-clouds CLOUD_A [...]
```

while somewhere on the system, exists a ``clouds.yml`` file:

```yml
clouds:
    CLOUD_A:
        auth_url: http://1.2.3.4:5000/v2.0
        username: yfried
        password: 123456
        project_name: rhos-qe-stage
    prod:
        auth_url: http://1.1.1.11:5000/v2.0
        username: Yair
        password: 12345678
        project_name: rhos-qe-ci

```

http://docs.openstack.org/developer/os-client-config/
